imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    downlaods_directory: '%kernel.project_dir%/web/uploads'
    bin_directory: '%kernel.project_dir%/bin'

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    assets:
#        font_awesome_brands_400_eot:
#            inputs: '@AppBundle/Resources/public/fonts/fa-brands-400.eot'
#            output: 'webfonts/fa-brands-400.eot'
#        font_awesome_brands_400_svg:
#            inputs: '@AppBundle/Resources/public/fonts/fa-brands-400.svg'
#            output: 'webfonts/fa-brands-400.svg'
#        font_awesome_brands_400_ttf:
#            inputs: '@AppBundle/Resources/public/fonts/fa-brands-400.ttf'
#            output: 'webfonts/fa-brands-400.ttf'
#        font_awesome_brands_400_woff:
#            inputs: '@AppBundle/Resources/public/fonts/fa-brands-400.woff'
#            output: 'webfonts/fa-brands-400.woff'
#        font_awesome_brands_400_woff2:
#            inputs: '@AppBundle/Resources/public/fonts/fa-brands-400.woff2'
#            output: 'webfonts/fa-brands-400.woff2'
#        font_awesome_regular_400_eot:
#            inputs: '@AppBundle/Resources/public/fonts/fa-regular-400.eot'
#            output: 'webfonts/fa-regular-400.eot'
#        font_awesome_regular_400_svg:
#            inputs: '@AppBundle/Resources/public/fonts/fa-regular-400.svg'
#            output: 'webfonts/fa-regular-400.svg'
#        font_awesome_regular_400_ttf:
#            inputs: '@AppBundle/Resources/public/fonts/fa-regular-400.ttf'
#            output: 'webfonts/fa-regular-400.ttf'
#        font_awesome_regular_400_woff:
#            inputs: '@AppBundle/Resources/public/fonts/fa-regular-400.woff'
#            output: 'webfonts/fa-regular-400.woff'
#        font_awesome_regular_400_woff2:
#            inputs: '@AppBundle/Resources/public/fonts/fa-regular-400.woff2'
#            output: 'webfonts/fa-regular-400.woff2'
#        font_awesome_eot:
#            inputs: '@AppBundle/Resources/public/fonts/fa-solid-900.eot'
#            output: 'webfonts/fa-solid-900.eot'
#        font_awesome_woff2:
#            inputs: '@AppBundle/Resources/public/fonts/fa-solid-900.woff2'
#            output: 'webfonts/fa-solid-900.woff2'
#        font_awesome_woff:
#            inputs: '@AppBundle/Resources/public/fonts/fa-solid-900.woff'
#            output: 'webfonts/fa-solid-900.woff'
        css_app:
            inputs:
                - '@AppBundle/Resources/public/css/bootstrap/*'
                - '@AppBundle/Resources/public/css/bootAdmin/bootadmin.min.css'
                - '@AppBundle/Resources/public/css/all.min.css'
        js_app:
            inputs:
                - '@AppBundle/Resources/public/js/jquery/*'
                - '@AppBundle/Resources/public/js/popper.min.js'
                - '@AppBundle/Resources/public/js/bootstrap/*'
                - '@AppBundle/Resources/public/js/bootAdmin/bootadmin.min.js'